C---------------------------------------------------------------
C file lib_f.f
C Equation system to simulate metabolic and/or isotopic dynamics.
C This code is automatically generated by IsoSim, do not edit.
C---------------------------------------------------------------

C initialiser for parameter common block
      subroutine initmod(odeparms)
       external odeparms
       double precision parms(7)
       common /myparms/parms
       call odeparms(7, parms)
       return
      end

C calculate derivatives
      subroutine derivs (neq, t, y, ydot, yout, ip)
       implicit none
       double precision t
       double precision y(59)
       double precision ydot(59)
       double precision yout(*)
       integer neq, ip(*)
C   declare METABOLITES
       double precision Sout
       double precision Sin
       double precision A
       double precision D
       double precision F
       double precision B
       double precision C
       double precision E
       double precision G
       double precision K
       double precision H
       double precision I
       double precision J
       double precision L
       double precision M
       double precision N
       double precision O
       double precision P
C   declare VARIABLES
       double precision v3 
       double precision v5 
       double precision v4 
       double precision v7 
       double precision v8 
       double precision v9 
       double precision v11 
       double precision v12 
       double precision v13 
       double precision v14 
       double precision v15 
       double precision v16 
       double precision v17 
       double precision v18 
       double precision v19 
       double precision v20 
C   declare FLUXES
       double precision r1
       double precision r2
       double precision r3
       double precision r4
       double precision r5
       double precision r6for
       double precision r6rev
       double precision r7
       double precision r8
       double precision r9
       double precision r10
       double precision r11
       double precision r12
       double precision r13
       double precision r14
       double precision r15
       double precision r16
       double precision r17
       double precision r18
       double precision r19
       double precision r20
C   declare KINETIC PARAMETERS
       double precision v1
       double precision v2
       double precision v6
       double precision v10
       double precision v6xch
       double precision v6f
       double precision v6r
C   set values of MODEL PARAMETERS
       common /myparms/ v1,
     * v2,
     * v6,
     * v10,
     * v6xch,
     * v6f,
     * v6r
C   set variables with analytical functions
       y(1)=0.0+0.0*t
       y(2)=1.0+0.0*t
C   calculate METABOLITE concentrations by summing EMU concentrations
       Sout=y(42)
       Sin=y(43)
       A=y(44)
       D=y(45)
       F=y(46)
       B=y(47)
       C=y(48)
       E=y(49)
       G=y(50)
       K=y(51)
       H=y(52)
       I=y(53)
       J=y(54)
       L=y(55)
       M=y(56)
       N=y(57)
       O=y(58)
       P=y(59)
C   calculate VARIABLES
       v3 = v1-v2
       v5 = v6f-v6r
       v4 = v2-v5
       v7 = v3
       v8 = v6f-v6r+v7
       v9 = v8-v10
       v11 = v10
       v12 = v11
       v13 = v12
       v14 = v12
       v15 = v14
       v16 = v15
       v17 = v16
       v18 = v4+v9
       v19 = v18+v17
       v20 = v19
C   calculate FLUXES
       r1=v1
       r2=v2
       r3=v3
       r4=v4
       r5=v5
       r6for=v6f
       r6rev=v6r
       r7=v7
       r8=v8
       r9=v9
       r10=v10
       r11=v11
       r12=v12
       r13=v13
       r14=v14
       r15=v15
       r16=v16
       r17=v17
       r18=v18
       r19=v19
       r20=v20
C   ---------------
C   equation system
C   ---------------
C   calculate derivatives of EMU concentrations
       ydot(1)=0
       ydot(2)=0
       ydot(3)=r1*(y(1)/Sout)+r2*(-y(3)/Sin)+r3*(-y(3)/Sin)
       ydot(4)=r1*(y(2)/Sout)+r2*(-y(4)/Sin)+r3*(-y(4)/Sin)
       ydot(5)=r2*(y(3)/Sin)+r4*(-y(5)/A)+r5*(-y(5)/A)
       ydot(6)=r2*(y(4)/Sin)+r4*(-y(6)/A)+r5*(-y(6)/A)
       ydot(7)=r3*(y(3)/Sin)+r7*(-y(7)/D)
       ydot(8)=r3*(y(4)/Sin)+r7*(-y(8)/D)
       ydot(9)=r4*(y(5)/A)+r9*(y(11)/E)+r18*(-y(9)/F)
       ydot(10)=r4*(y(6)/A)+r9*(y(12)/E)+r18*(-y(10)/F)
       ydot(11)=r9*(-y(11)/E)+r8*(y(15)/C)+r10*(-y(11)/E)
       ydot(12)=r9*(-y(12)/E)+r8*(y(16)/C)+r10*(-y(12)/E)
       ydot(13)=r5*(y(5)/A)+r6rev*(y(15)/C)+r6for*(-y(13)/B)
       ydot(14)=r5*(y(6)/A)+r6rev*(y(16)/C)+r6for*(-y(14)/B)
       ydot(15)=r6rev*(-y(15)/C)+r6for*(y(13)/B)+r7*(y(7)/D)+r8*
     &(-y(15)/C)
       ydot(16)=r6rev*(-y(16)/C)+r6for*(y(14)/B)+r7*(y(8)/D)+r8*
     &(-y(16)/C)
       ydot(17)=r10*(y(11)/E)+r11*(-y(17)/G*y(21)/K-y(17)/G*y(22
     &)/K)
       ydot(18)=r10*(y(12)/E)+r11*(-y(18)/G*y(21)/K-y(18)/G*y(22
     &)/K)
       ydot(19)=r13*(-y(19)/I)+r12*(y(26)/H)
       ydot(20)=r13*(-y(20)/I)+r12*(y(27)/H)
       ydot(21)=r13*(y(19)/I)+r11*(-y(21)/K)
       ydot(22)=r13*(y(20)/I)+r11*(-y(22)/K)
       ydot(23)=r11*(y(17)/G*y(21)/K)+r12*(-y(23)/H)
       ydot(24)=r11*(y(18)/G*y(21)/K+y(17)/G*y(22)/K)+r12*(-y(24
     &)/H)
       ydot(25)=r11*(y(18)/G*y(22)/K)+r12*(-y(25)/H)
       ydot(26)=r12*(-y(26)/H)+r11*(y(17)/G)
       ydot(27)=r12*(-y(27)/H)+r11*(y(18)/G)
       ydot(28)=r12*(-y(28)/H)+r11*(y(21)/K)
       ydot(29)=r12*(-y(29)/H)+r11*(y(22)/K)
       ydot(30)=r12*(y(28)/H)+r14*(-y(30)/J)
       ydot(31)=r12*(y(29)/H)+r14*(-y(31)/J)
       ydot(32)=r14*(y(30)/J)+r15*(-y(32)/L)
       ydot(33)=r14*(y(31)/J)+r15*(-y(33)/L)
       ydot(34)=r15*(y(32)/L)+r16*(-y(34)/M)
       ydot(35)=r15*(y(33)/L)+r16*(-y(35)/M)
       ydot(36)=r16*(y(34)/M)+r17*(-y(36)/N)
       ydot(37)=r16*(y(35)/M)+r17*(-y(37)/N)
       ydot(38)=r17*(y(36)/N)+r18*(y(9)/F)+r19*(-y(38)/O)
       ydot(39)=r17*(y(37)/N)+r18*(y(10)/F)+r19*(-y(39)/O)
       ydot(40)=r19*(y(38)/O)+r20*(-y(40)/P)
       ydot(41)=r19*(y(39)/O)+r20*(-y(41)/P)
       ydot(42)=0
       ydot(43)=r1*(y(42)/Sout*y(43)/Sin)+r2*(-y(43)/Sin*y(44)/A
     &)+r3*(-y(43)/Sin*y(45)/D)
       ydot(44)=r2*(y(43)/Sin*y(44)/A)+r4*(-y(44)/A*y(46)/F)+r5*
     &(-y(44)/A*y(47)/B)
       ydot(45)=r3*(y(43)/Sin*y(45)/D)+r7*(-y(45)/D*y(48)/C)
       ydot(46)=r4*(y(44)/A*y(46)/F)+r9*(y(49)/E*y(46)/F)+r18*(-
     &y(46)/F*y(58)/O)
       ydot(47)=r5*(y(44)/A*y(47)/B)+r6for*(-y(47)/B*y(48)/C)+r6
     &rev*(y(48)/C*y(47)/B)
       ydot(48)=r6for*(y(47)/B*y(48)/C)+r6rev*(-y(48)/C*y(47)/B)
     &+r7*(y(45)/D*y(48)/C)+r8*(-y(48)/C*y(49)/E)
       ydot(49)=r8*(y(48)/C*y(49)/E)+r9*(-y(49)/E*y(46)/F)+r10*(
     &-y(49)/E*y(50)/G)
       ydot(50)=r10*(y(49)/E*y(50)/G)+r11*(-y(50)/G*y(51)/K*y(52
     &)/H)
       ydot(51)=r11*(-y(50)/G*y(51)/K*y(52)/H)+r13*(y(53)/I*y(51
     &)/K)
       ydot(52)=r11*(y(50)/G*y(51)/K*y(52)/H)+r12*(-y(52)/H*y(53
     &)/I*y(54)/J)
       ydot(53)=r12*(y(52)/H*y(53)/I*y(54)/J)+r13*(-y(53)/I*y(51
     &)/K)
       ydot(54)=r12*(y(52)/H*y(53)/I*y(54)/J)+r14*(-y(54)/J*y(55
     &)/L)
       ydot(55)=r14*(y(54)/J*y(55)/L)+r15*(-y(55)/L*y(56)/M)
       ydot(56)=r15*(y(55)/L*y(56)/M)+r16*(-y(56)/M*y(57)/N)
       ydot(57)=r16*(y(56)/M*y(57)/N)+r17*(-y(57)/N*y(58)/O)
       ydot(58)=r17*(y(57)/N*y(58)/O)+r18*(y(46)/F*y(58)/O)+r19*
     &(-y(58)/O*y(59)/P)
       ydot(59)=r19*(y(58)/O*y(59)/P)+r20*(-y(59)/P)
       return
      end
C---------------------------------------------------------------
C end of file lib_f.f
C---------------------------------------------------------------
