C---------------------------------------------------------------
C file lib_f_S_E.f
C Equation system to simulate metabolic and/or isotopic dynamics.
C This code is automatically generated by IsoSim, do not edit.
C---------------------------------------------------------------

C initialiser for parameter common block
      subroutine initmod(odeparms)
       external odeparms
       double precision parms(1)
       common /myparms/parms
       call odeparms(1, parms)
       return
      end

C calculate derivatives
      subroutine derivs (neq, t, y, ydot, yout, ip)
       implicit none
       double precision t
       double precision y(6)
       double precision ydot(6)
       double precision yout(*)
       integer neq, ip(*)
C   declare METABOLITES
       double precision C
       double precision E
C   declare FLUXES
       double precision r8
       double precision rout
C   declare KINETIC PARAMETERS
       double precision v8
C   set values of MODEL PARAMETERS
       common /myparms/ v8
C   set variables with analytical functions
       y(1)=1-(1-((1)/(1+exp(-(-2.59190642171133)*(t-(1.21702809
     &757355))))+(0.0191404741453833)))
       y(2)=1-((1)/(1+exp(-(-2.59190642171133)*(t-(1.21702809757
     &355))))+(0.0191404741453833))
C   calculate METABOLITE concentrations by summing EMU concentrations
       C=y(5)
       E=y(6)
C   calculate FLUXES
       r8=v8
       rout=v8
C   ---------------
C   equation system
C   ---------------
C   calculate derivatives of EMU concentrations
       ydot(1)=0
       ydot(2)=0
       ydot(3)=r8*(y(1)/C)+rout*(-y(3)/E)
       ydot(4)=r8*(y(2)/C)+rout*(-y(4)/E)
       ydot(5)=0
       ydot(6)=r8*(y(5)/C*y(6)/E)+rout*(-y(6)/E)
       return
      end
C---------------------------------------------------------------
C end of file lib_f_S_E.f
C---------------------------------------------------------------
